### ISSUE TITLE
Uploading local package

### ISSUE THREAD

**Issue by rolfmblindgren** [RevolutionAnalytics/AzureML#107] opened 2016-06-05 17:40 UTC
Consider the following code, which basically uploads a library and fails to attempt to install it.

```
localCRAN <- "~/Library/R/miniCRAN"
uri <- paste0("file:///", normalizePath(localCRAN))
options(repos = c(CRAN = uri))

library(AzureML)
library(talection)
library(rmarkdown)

ws <- workspace()

while (nrow(services(ws,name="Talection-fun")) != 0) {
  deleteWebService(ws, "Talection-fun")
}

fun <- function (b5) {
    if (R.version[["os"]]=="mingw32" && ! require(talection)) {
        install.packages(
            "src/rmarkdown_0.9.6.zip",
            lib=".",
            type="win.binary",
            repos=NULL,
            verbose=TRUE)
    }
    ans <- as.data.frame(c("Finished"))
}

ep <- publishWebService (
  ws,
  fun = fun,
  name = "Talection-fun",
  inputSchema = test,
  outputSchema = list(
    ans = "character"
  ),
  packages = c("rmarkdown")
)

print(consume(ep,test))
```
This returns

```
Request failed with status 401. Waiting 9.3 seconds before retry
..........Request failed with status 400. Waiting 19.5 seconds before retry
....................Request failed with status 400. Waiting 24.8 seconds before retry
.........................Request failed with status 400. Waiting 67.4 seconds before retry
....................................................................Request failed with status 400. Waiting 219.3 seconds before retry
............................................................................................................................................................................................................................Request failed with status 400. Waiting 473.1 seconds before retry
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Error: AzureML returns error code:
HTTP status code : 400
AzureML error code  : LibraryExecutionError

Module execution encountered an internal library error.
```

There are really two issues here.

1. The function `fun` is evaluated before it is uploaded to `AzureML`. So the if test is to ensure that nothing is installed until after upload.
2. The `rmarkdown` package seems to be uploaded, but not installed. The `install.package` invocation should to the trick, but doesn't. Any obvious mistakes here?

**Comment by andrie** [comment] 2016-06-16 15:44
This has also been reported in #109.

We will take a look at this and report progress in #109.

**Comment by andrie** [comment] 2016-06-26 13:10
This is now fixed in version 0.2.6 of `miniCRAN` (not yet on CRAN)

To try this, first install `miniCRAN` from github, using:

```
devtools::install_github("RevolutionAnalytics/miniCRAN")
```

Then create a local repository using miniCRAN, as you have already done.

Finally, in the `AzureML` package, you simply have to point to your local miniCRAN, using `file:///`, as you already do, and add the required packages to the `publishWebservice(..., packages = "...")` argument.

All the packages you specify in the `packages` argument get automatically installed. You should not try to install this in your code.

**Comment by andrie** [comment] 2016-06-26 13:11
The underlying root cause was behaviour in `download.packages()` and we implemented a workaround in `miniCRAN` using https://github.com/RevolutionAnalytics/miniCRAN/issues/76

**Comment by rolfmblindgren** [comment] 2016-06-27 18:41
I'm sure I'm doing something wrong here … 

I've used PkgDep to make sure that I have absolutely all dependencies in my miniCRAN.

I've reinstalled the miniCRAN package. Do I have to create the library from scratch again?

The packages still seem not to be installed. What would be the best way to trace the issue?

**Comment by andrie** [comment] 2016-06-28 23:55
Please provide more detail:

* How did you install the updated miniCRAN package?
* What is the version number?

You need to install directly from github - the update is not yet on CRAN, and you need version 0.2.6.

You don't need to re-create the local miniCRAN repository. The issue is not in creating the local repo, but in (invisibly) creating a miniCRAN from a local file:/// miniCRAN repo. This is what was fixed in the new version.

**Comment by rolfmblindgren** [comment] 2016-07-28 13:05
I'm running R 3.1.3 on Windows 10.

AzureML is at version 0.2.12, miniCRAN is at version 0.2.6.

I get an error message if I remove `talection_0.01.zip` from miniCRAN. So obviously it's being looked for.

The exact code I'm working on , is this:

```
localCRAN <- "C:\\Users\\ruser\\Documents\\R\\miniCRAN"
uri <- paste0("file:///", normalizePath(localCRAN))
options(repos = c(CRAN = uri))

library(AzureML)

ws <- workspace()

while (nrow(services(ws,name="Talection-b5tobelbin")) != 0) {
  deleteWebService(ws, "Talection-b5tobelbin")
}

fun <- function (b5) {
  require(talection)
  res <- as.data.frame(b5tobelbin(b5[[1]]))
}

test <- as.data.frame(
  cbind(
    c(0.0,  0.3,  0.0,  0.0,  0.0),
    c(0.0,  0.0,  0.0, -0.4,  0.0),
    c(0,      0,    0,    0,    0))
)


ep <- publishWebService (
  ws,
  fun = fun,
  name = "Talection-b5tobelbin",
  inputSchema = test,
  packages = c("talection","jsonlite","psych")
)

print(consume(ep,test))

options(repos = c(CRAN = "http://cran.uib.no/"))
```
And here's the error message:

```
> source('~/WebServices/WebServices.R')
converting `inputSchema` to data frame
converting `function_output` to data frame
Created new folder: C:/Users/ruser/AppData/Local/Temp/RtmpYjyLgo/dir223850695723/packages/bin/windows/contrib/3.1
Request failed with status 401. Waiting 4.5 seconds before retry
.....
Error: AzureML returns error code:
HTTP status code : 400
AzureML error code  : LibraryExecutionError

Module execution encountered an internal library error.
The following error occurred during evaluation of R script: R_tryEval: return error: Error in as.data.frame(b5tobelbin(b5[[1]])) : 
  could not find function "b5tobelbin"
```

I've no clue since I can't trace what happens internally. Is `talection_0.01.zip` uploaded, but fails to install? I bult the package, and it installs fine locally. 

Any and all hints and suggestions are welcome.

**Comment by andrie** [comment] 2016-08-16 13:38
Closing as duplicate of #109 

If you're still having problems, please install the latest version of `miniCRAN` and try again.

**Comment by rolfmblindgren** [comment] 2016-08-16 20:42
So I've done, and no more luck – it's the same miniCRAN package as I used last time, installed using install_github.

I'm starting to wonder if the problem may be with the package itself. Is there a way I can obtain more comprehensive debug information?

**Comment by andrie** [comment] 2016-08-19 09:12
I have now been able to reproduce. I think the root cause is in `miniCRAN`.

Re-opening.

**Comment by andrie** [comment] 2016-08-19 11:10
There is a simple workaround. Specify `winslash = "/"` in `normalizePath()`.

```r
localCRAN <- "C:\\Users\\ruser\\Documents\\R\\miniCRAN"
uri <- paste0("file:///", normalizePath(localCRAN, winslash = "/"))
options(repos = c(CRAN = uri))
```

I am working on getting this fixed in `miniCRAN`.

**Comment by rolfmblindgren** [comment] 2016-08-19 13:01
I can confirm that it works now.

Thanks so much!

**Closed** 2016-08-19 21:40 UTC
Labels: duplicate
