### ISSUE TITLE
Upload packages from a local repository using `publishWebservice()`

### ISSUE THREAD

**Issue by jamieo-ms** [RevolutionAnalytics/AzureML#109] opened 2016-06-08 16:59 UTC
In order to get custom packages uploaded through AzureML, they need to be available in a local repository.  However, `download.packages` (called from `packageEnv`) does NOT copy local packages but just returns the path to the package in the existing repository.

**Comment by andrie** [comment] 2016-06-16 10:57
I'm not sure I follow.

We don't use `download.packages()` directly in `packageEnv()` (or anywhere else). The downloading of packages is pushed to `makeRepo()`.

I have just tested this, and the windows binaries do in fact get downloaded to a local temporary folder.

After downloading, `packageEnv()` then zips up the content of this temp folder - this zip file gets uploaded to Azure ML Studio.

@jamieo-ms  Can you please expand on this issue?

**Comment by jamieo-ms** [comment] 2016-06-16 14:15
My bad, this is happening in `makeRepo` not `packageEnv`.  Binaries get downloaded *only if the repository is non-local*.  If you create a new package and put it in a local repo setup with miniCRAN, it gets ignored.


-----------------------------------------------------
Jamie F Olson
Senior Data Scientist
Microsoft
1-610-727-3079
jamieo@microsoft.com<mailto:jamieo@microsoft.com>

**Comment by andrie** [comment] 2016-06-16 16:25
To resolve this, we need to expose an option to change the repository used in `publishWebservice()`.

Currently the repo is hard coded in `packageEnv()` with no option to change this.

**Comment by jamieo-ms** [comment] 2016-06-17 06:49
The repo only reverts to the hard-coded in URL in `options("repos")` is NULL

**Comment by andrie** [comment] 2016-06-17 13:35
I have traced the root cause of this.

In `utils::download.packages()`, the package does not actually get downloaded if the `repos` contains `file://` as the prefix. Instead, the function returns the local file location of the existing package, rather than making a copy in the `destdir`.

Thus, as it stands, you can't use `miniCRAN` to create a `miniCRAN` from an existing `miniCRAN` on the same machine.

I can think of two ways to resolve this:
1. Change `miniCRAN` to create a copy
2. Add a line in `AzureML` to test for an existing local `miniCRAN` and upload this.

Option 2 has the downside that it will upload the entire existing `miniCRAN` rather than creating a new one. But this may well be exactly what the use case is.

**Comment by andrie** [comment] 2016-07-13 09:51
This has now been fixed in `miniCRAN` version 0.2.16, which is now available on CRAN.

**Closed** 2016-08-16 13:29 UTC
Labels: enhancement
